/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.TituloPropiedad;
/**
 *
 * @author javs
 */
public class CasillaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }
    
    public void setCasilla(Casilla casilla, int numero) {
        labelPrecio.setVisible(false);
        labelPropietario.setVisible(false);
        textfieldPrecio.setVisible(false);
        textfieldPropietario.setVisible(false);
        textfieldNombre.setText(casilla.getNombre());
        textfieldNumero.setText(String.valueOf(numero));
        textfieldTipo.setText(casilla.getTipo());
        if (casilla.getTipo().equals("Calle")) {
            TituloPropiedad propiedad = ((CasillaCalle)casilla).getTituloPropiedad();
            if (propiedad.tienePropietario()) {
                textfieldPropietario.setText(propiedad.getPropietario().getNombre());
                labelPrecio.setText("Precio de alquiler");
                textfieldPrecio.setText(String.valueOf(propiedad.getPrecioAlquiler()));
                labelPropietario.setVisible(true);
                textfieldPropietario.setVisible(true);
            } else {
                labelPrecio.setText("Precio de compra");
                textfieldPrecio.setText(String.valueOf(propiedad.getPrecioCompra()));
            } 
            labelPrecio.setVisible(true);
            textfieldPrecio.setVisible(true);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelPropietario = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        textfieldNombre = new javax.swing.JTextField();
        textfieldNumero = new javax.swing.JTextField();
        textfieldTipo = new javax.swing.JTextField();
        textfieldPrecio = new javax.swing.JTextField();
        textfieldPropietario = new javax.swing.JTextField();

        labelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNombre.setText("Nombre");

        labelTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTipo.setText("Tipo");

        labelPrecio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelPrecio.setText("Precio de alquiler");

        labelPropietario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelPropietario.setText("Propietario");

        labelNumero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNumero.setText("Número");

        textfieldNombre.setEditable(false);
        textfieldNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldNombre.setText("jTextField1");

        textfieldNumero.setEditable(false);
        textfieldNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldNumero.setText("jTextField2");

        textfieldTipo.setEditable(false);
        textfieldTipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldTipo.setText("jTextField3");

        textfieldPrecio.setEditable(false);
        textfieldPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldPrecio.setText("jTextField4");

        textfieldPropietario.setEditable(false);
        textfieldPropietario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldPropietario.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelNumero)
                    .addComponent(labelTipo)
                    .addComponent(labelPrecio)
                    .addComponent(labelPropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(textfieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(textfieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(textfieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPropietario)
                    .addComponent(textfieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelPropietario;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField textfieldNombre;
    private javax.swing.JTextField textfieldNumero;
    private javax.swing.JTextField textfieldPrecio;
    private javax.swing.JTextField textfieldPropietario;
    private javax.swing.JTextField textfieldTipo;
    // End of variables declaration//GEN-END:variables
}
