/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.SalidasCarcel;
import civitas.OperacionesJuego;
import javax.swing.JOptionPane;
import civitas.Jugador;
/**
 *
 * @author javs
 */
public class CivitasView extends javax.swing.JFrame {
    private CivitasJuego juego;
    private JugadorPanel jugadorPanel;
    private GestionarDialog gestionarD;
    private CasillaPanel casillaPanel;
    
    public void setCivitasJuego(CivitasJuego juego) {
        this.juego = juego;
        setVisible(true);
    }
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        casillaPanel = new CasillaPanel();
        contenedorVistaJugador.add(jugadorPanel);
        contenedorCasilla.add(casillaPanel);
        repaint();
        revalidate();
    }
    
    public void actualizarVista() {
        // System.out.println("mmmmm " + juego.getJugadorActual());
        labelRanking.setVisible(false);
        contenedorRanking.setVisible(false);
        jugadorPanel.setJugador(juego.getJugadorActual());
        casillaPanel.setCasilla(juego.getCasillaActual(), juego.getJugadorActual().getNumCasillaActual());
        if (juego.finalDelJuego()) {
            labelRanking.setVisible(true);
            contenedorRanking.setVisible(true);
            int n = 1;
            for (Jugador i : juego.ranking()) {
                textareaRanking.append(String.valueOf(n) + "°: \n" + i.toString() + "\n");
                n++;   
            }
            //textareaRanking.setText(juego.ranking().toString());
            pack();
            repaint();
            revalidate();
        }
    }
    
    public void mostrarSiguienteOperacion(OperacionesJuego operacion) {
        textfieldSiguienteOperacion.setText(operacion.toString());
        actualizarVista();
    }
    
    public void mostrarEventos() {
        DiarioDialog diarioD = new DiarioDialog(this);
    }
    
    public Respuestas comprar() {
        int opcion = JOptionPane.showConfirmDialog(null, "Quieres comprar la calle actual?",
                "Compra", JOptionPane.YES_NO_OPTION);
        return Respuestas.values()[opcion];
    }
    
    public void gestionar() {
        gestionarD = new GestionarDialog(this);
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.gestionar(juego.getJugadorActual());
        //gestionarD.setVisible(true);
    }
    
    public int getGestion() {
        return gestionarD.getGestion();
    }
    
    public int getPropiedad() {
        return gestionarD.getPropiedad();
    }
    
    public SalidasCarcel salirCarcel() {
        String[] opciones = {"Pagando", "Tirando" };
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel",
                "Salir de la cárcel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, 
                null, opciones, opciones[0]);
        return SalidasCarcel.values()[respuesta];
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCivitas = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        textfieldSiguienteOperacion = new javax.swing.JTextField();
        labelRanking = new javax.swing.JLabel();
        labelSiguienteOp = new javax.swing.JLabel();
        contenedorCasilla = new javax.swing.JPanel();
        labelCasillaActual = new javax.swing.JLabel();
        contenedorRanking = new javax.swing.JScrollPane();
        textareaRanking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        labelCivitas.setBackground(new java.awt.Color(139, 0, 0));
        labelCivitas.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        labelCivitas.setForeground(new java.awt.Color(139, 0, 0));
        labelCivitas.setText("Civitas");

        textfieldSiguienteOperacion.setEditable(false);
        textfieldSiguienteOperacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldSiguienteOperacion.setText("jTextField1");
        textfieldSiguienteOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSiguienteOperacionActionPerformed(evt);
            }
        });

        labelRanking.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelRanking.setText("Ranking");

        labelSiguienteOp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSiguienteOp.setText("Siguiente operación");

        labelCasillaActual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCasillaActual.setText("Casilla actual");

        textareaRanking.setEditable(false);
        textareaRanking.setColumns(20);
        textareaRanking.setRows(5);
        contenedorRanking.setViewportView(textareaRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCivitas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelSiguienteOp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCasillaActual)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(contenedorCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRanking)
                            .addComponent(contenedorRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCivitas)
                    .addComponent(textfieldSiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSiguienteOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCasillaActual)
                    .addComponent(labelRanking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenedorRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldSiguienteOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSiguienteOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSiguienteOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorCasilla;
    private javax.swing.JScrollPane contenedorRanking;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JLabel labelCasillaActual;
    private javax.swing.JLabel labelCivitas;
    private javax.swing.JLabel labelRanking;
    private javax.swing.JLabel labelSiguienteOp;
    private javax.swing.JTextArea textareaRanking;
    private javax.swing.JTextField textfieldSiguienteOperacion;
    // End of variables declaration//GEN-END:variables
}
