/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Jugador;
import civitas.JugadorEspeculador;
import civitas.TituloPropiedad;
import java.util.ArrayList;
/**
 *
 * @author javs
 */
public class JugadorPanel extends javax.swing.JPanel {

    Jugador jugador;
    CasillaPanel casillaPanel;
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
        textfieldNombre.setText(jugador.getNombre());
        textfieldSaldo.setText(String.valueOf(jugador.getSaldo()));
        textfieldEncarcelado.setText(jugador.isEncarcelado() ? "Sí" : "No");
        textfieldEspeculador.setText(jugador instanceof JugadorEspeculador ? "Sí" : "No");
        textfieldSalvoconducto.setText(jugador.tieneSalvoconducto() ? "Sí" : "No");
        labelPropiedades.setVisible(false);
        labelNroCasas.setVisible(false);
        labelNroHoteles.setVisible(false);
        labelNombrePropiedad.setVisible(false);
        labelHipotecada.setVisible(false);
        repaint();
        rellenaPropiedades(jugador.getPropiedades());
    }
    
    private void rellenaPropiedades(ArrayList<TituloPropiedad> lista) {
        propiedades.removeAll();
        if (!lista.isEmpty()) {
            labelPropiedades.setVisible(true);
            labelNroCasas.setVisible(true);
            labelNroHoteles.setVisible(true);
            labelNombrePropiedad.setVisible(true);
            labelHipotecada.setVisible(true);   
        }
        for (TituloPropiedad t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        repaint();
        revalidate();
    }
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        labelEncarcelado = new javax.swing.JLabel();
        labelEspeculador = new javax.swing.JLabel();
        textfieldNombre = new javax.swing.JTextField();
        textfieldSaldo = new javax.swing.JTextField();
        textfieldEncarcelado = new javax.swing.JTextField();
        textfieldEspeculador = new javax.swing.JTextField();
        labelSalvoconducto = new javax.swing.JLabel();
        textfieldSalvoconducto = new javax.swing.JTextField();
        labelPropiedades = new javax.swing.JLabel();
        labelNombrePropiedad = new javax.swing.JLabel();
        labelNroCasas = new javax.swing.JLabel();
        labelNroHoteles = new javax.swing.JLabel();
        labelHipotecada = new javax.swing.JLabel();
        propiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        labelNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNombre.setText("Nombre");

        labelSaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSaldo.setText("Saldo");

        labelEncarcelado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEncarcelado.setText("̉Encarcelado");

        labelEspeculador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelEspeculador.setText("Especulador");

        textfieldNombre.setEditable(false);
        textfieldNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldNombre.setText("jTextField1");
        textfieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNombreActionPerformed(evt);
            }
        });

        textfieldSaldo.setEditable(false);
        textfieldSaldo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldSaldo.setText("jTextField2");

        textfieldEncarcelado.setEditable(false);
        textfieldEncarcelado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldEncarcelado.setText("jTextField3");

        textfieldEspeculador.setEditable(false);
        textfieldEspeculador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldEspeculador.setText("jTextField4");
        textfieldEspeculador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldEspeculadorActionPerformed(evt);
            }
        });

        labelSalvoconducto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSalvoconducto.setText("Salvoconducto");

        textfieldSalvoconducto.setEditable(false);
        textfieldSalvoconducto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textfieldSalvoconducto.setText("jTextField1");

        labelPropiedades.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelPropiedades.setText("Propiedades");

        labelNombrePropiedad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNombrePropiedad.setText("Nombre");

        labelNroCasas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNroCasas.setText("N° de casas");

        labelNroHoteles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelNroHoteles.setText("N° de hoteles");

        labelHipotecada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelHipotecada.setText("Hipotecada");

        propiedades.setMaximumSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Jugador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(labelSalvoconducto)
                            .addComponent(labelSaldo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(labelEncarcelado))
                            .addComponent(labelEspeculador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldSalvoconducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPropiedades)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombrePropiedad)
                                    .addComponent(labelNroCasas)
                                    .addComponent(labelNroHoteles)
                                    .addComponent(labelHipotecada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(textfieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSaldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEncarcelado)
                            .addComponent(textfieldEncarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEspeculador)
                            .addComponent(textfieldEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSalvoconducto)
                            .addComponent(textfieldSalvoconducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPropiedades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombrePropiedad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNroCasas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNroHoteles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelHipotecada))
                            .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNombreActionPerformed

    private void textfieldEspeculadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldEspeculadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldEspeculadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEncarcelado;
    private javax.swing.JLabel labelEspeculador;
    private javax.swing.JLabel labelHipotecada;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombrePropiedad;
    private javax.swing.JLabel labelNroCasas;
    private javax.swing.JLabel labelNroHoteles;
    private javax.swing.JLabel labelPropiedades;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSalvoconducto;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField textfieldEncarcelado;
    private javax.swing.JTextField textfieldEspeculador;
    private javax.swing.JTextField textfieldNombre;
    private javax.swing.JTextField textfieldSaldo;
    private javax.swing.JTextField textfieldSalvoconducto;
    // End of variables declaration//GEN-END:variables
}
